kind: pipeline
type: docker
name: default

clone:
  depth: 1

platform:
  os: linux
  arch: arm64

node:
  cloud: oracle
  location: tokyo

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: gomodcache
    host:
      path: /var/docker/drone-runner/cache/gomod

steps:
  # Multi-platform build using built-in buildx
  - name: build-docker
    image: docker:24-dind  # 使用更新的Docker版本
    when:
      event:
        - tag
    environment:
      DOCKER_REGISTRY_PASSWORD:
        from_secret: registry-password
      DOCKER_BUILDKIT: "1"  # 启用BuildKit
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: gomodcache
        path: /go/pkg/mod
    commands:
      # 登录Docker Hub
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login --username=cloverzrg --password-stdin
      
      # 创建并使用buildx builder实例
      - docker buildx create --use --name multiarch-builder --driver docker-container
      
      # 构建frps镜像
      - |
        docker buildx build \
          --platform linux/arm64,linux/amd64,linux/386 \
          --tag cloverzrg/frps-docker:$DRONE_TAG \
          --tag cloverzrg/frps-docker:latest \
          --build-arg DRONE_TAG=$DRONE_TAG \
          --push \
          .
      
      # 构建frpc镜像
      - |
        docker buildx build \
          --file Dockerfile.frpc \
          --platform linux/arm64,linux/amd64,linux/386 \
          --tag cloverzrg/frpc-docker:$DRONE_TAG \
          --tag cloverzrg/frpc-docker:latest \
          --build-arg DRONE_TAG=$DRONE_TAG \
          --push \
          .
      
      # 清理builder实例
      - docker buildx rm multiarch-builder

  - name: build-docker-master
    image: docker:24-dind  # 使用更新的Docker版本
    when:
      branch:
        - master  # 修正：使用branch而不是event
      event:
        - push
    environment:
      DOCKER_REGISTRY_PASSWORD:
        from_secret: registry-password
      DOCKER_BUILDKIT: "1"  # 启用BuildKit
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: gomodcache
        path: /go/pkg/mod
    commands:
      # 登录Docker Hub
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login --username=cloverzrg --password-stdin
      
      # 创建并使用buildx builder实例
      - docker buildx create --use --name multiarch-builder-master --driver docker-container
      
      # 设置标签
      - export DRONE_TAG=master
      
      # 构建frps镜像
      - |
        docker buildx build \
          --platform linux/arm64,linux/amd64,linux/386 \
          --tag cloverzrg/frps-docker:latest \
          --build-arg DRONE_TAG=$DRONE_TAG \
          --push \
          .
      
      # 构建frpc镜像
      - |
        docker buildx build \
          --file Dockerfile.frpc \
          --platform linux/arm64,linux/amd64,linux/386 \
          --tag cloverzrg/frpc-docker:latest \
          --build-arg DRONE_TAG=$DRONE_TAG \
          --push \
          .
      
      # 清理builder实例
      - docker buildx rm multiarch-builder-master
