---
kind: pipeline
type: docker
name: default

clone:
  depth: 1

platform:
  os: linux
  arch: arm64


node:
  cloud: oracle
  location: tokyo

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: gomodcache
    host:
      path: /var/docker/drone-runner/cache/gomod

steps:
  - name: build-docker
    image: docker:dind
    when:
      event:
        - tag
    environment:
      password:
        from_secret: registry-password
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: cache-docker-buildx-0.14.1
        path: /root/.docker/cli-plugins
      - name: gomodcache
        path: /go/pkg/mod
    commands:
      - docker login --username=cloverzrg -p $password
      - build_node=$(docker buildx create --use)
      - echo 'build node:'$build_node
      - docker buildx build --platform linux/arm64,linux/amd64,linux/386 -t cloverzrg/frps-docker:$DRONE_TAG -t cloverzrg/frps-docker:latest --push --build-arg DRONE_TAG=$DRONE_TAG .
      - docker buildx build -f Dockerfile.frpc --platform linux/arm64,linux/amd64,linux/386 -t cloverzrg/frpc-docker:$DRONE_TAG -t cloverzrg/frpc-docker:latest --push --build-arg DRONE_TAG=$DRONE_TAG .
      - docker buildx rm $build_node

  - name: build-docker-master
    image: docker:dind
    when:
      branch:
        - master
      event:
        - push
    environment:
      password:
        from_secret: registry-password
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: gomodcache
        path: /go/pkg/mod
    commands:
      - DRONE_TAG=master
      - docker login --username=cloverzrg -p $password
      - build_node=$(docker buildx create --use)
      - echo 'build node:'$build_node
      - docker buildx build --platform linux/arm64,linux/amd64,linux/386 -t cloverzrg/frps-docker:latest --push --build-arg DRONE_TAG=$DRONE_TAG .
      - docker buildx build -f Dockerfile.frpc --platform linux/arm64,linux/amd64,linux/386 -t cloverzrg/frpc-docker:latest --push --build-arg DRONE_TAG=$DRONE_TAG .
      - docker buildx rm $build_node
