---
kind: pipeline
type: docker
name: default

clone:
  depth: 1

platform:
  os: linux
  arch: arm64


node:
  cloud: oracle
  location: tokyo

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: cache-docker-buildx-0.10.5
    host:
      path: /tmp/drone/cache/docker-buildx-0.10.5
  - name: gomodcache
    host:
      path: /var/docker/drone-runner/cache/gomod

steps:

  # Multi-platform build, downloading buildx only when not cached
  # @see: https://docs.drone.io/pipeline/docker/examples/services/docker/
  - name: build-docker
    image: docker:dind
    when:
      event:
        - tag
    environment:
      password:
        from_secret: registry-password
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: cache-docker-buildx-0.10.5
        path: /root/.docker/cli-plugins
      - name: gomodcache
        path: /go/pkg/mod
    commands:
      - |
        (
          set -x; \
          FILE=~/.docker/cli-plugins/docker-buildx; \
          [ ! -f $FILE ] && \
            wget -O $FILE https://github.com/docker/buildx/releases/download/v0.10.5/buildx-v0.10.5.linux-arm64 \
            && chmod +x $FILE \
          || true
        ) 
      - docker login --username=cloverzrg -p $password
      # - docker buildx create --use
      - docker buildx build --platform linux/arm64,linux/amd64,linux/386 -t cloverzrg/frps-docker:$DRONE_TAG -t cloverzrg/frps-docker:latest --push --build-arg DRONE_TAG=$DRONE_TAG .
      - docker buildx build -f Dockerfile.frpc --platform linux/arm64,linux/amd64,linux/386 -t cloverzrg/frpc-docker:$DRONE_TAG -t cloverzrg/frpc-docker:latest --push --build-arg DRONE_TAG=$DRONE_TAG .
