---
kind: pipeline
type: docker
name: default

clone:
  depth: 1

platform:
  os: linux
  arch: arm64
  

node:
  cloud: oracle
  location: tokyo
  
volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: cache-docker-buildx-0.6.1
    host:
      path: /tmp/drone/cache/docker-buildx-0.6.1
  - name: gomodcache
    host:
      path: /var/docker/drone-runner/cache/gomod

steps:

# Multi-platform build, downloading buildx only when not cached
# @see: https://docs.drone.io/pipeline/docker/examples/services/docker/
- name: build-docker
  image: docker:dind
  environment:
    password:
      from_secret: registry-password
  volumes:
    - name: dockersock
      path: /var/run/docker.sock
    - name: cache-docker-buildx-0.6.1
      path: /root/.docker/cli-plugins
    - name: gomodcache
      path: /go/pkg/mod
  
  commands:
    - echo $PATH
    - |
        (
          set -x; \
          FILE=~/.docker/cli-plugins/docker-buildx; \
          [ ! -f $FILE ] && \
            wget -O $FILE https://github.com/docker/buildx/releases/download/v0.6.1/buildx-v0.6.1.linux-arm64 \
            && chmod +x $FILE \
          || true
        )
    - echo ${PATH}
    - echo ${password}
    - env
    - docker login --username=cloverzrg -p "${password}"
    - docker buildx create --use
    - |
        docker buildx build \
          --platform linux/arm,linux/arm64,linux/amd64,linux/386 \
          --tag cloverzrg/frps-test:0.37.1 \
          --tag cloverzrg/frps-test:latest \
          --push \
          .
